[workspace]
members = ["cjxe", "cjxe_examples", "cjxe_tests", "cjxe_integration_tests"]
build-members = ["cjxe", "cjxe_examples", "cjxe_tests", "cjxe_integration_tests"]
test-members = ["cjxe_examples", "cjxe_tests"]
