name: ci

on: [push, pull_request]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Zxilly/setup-cangjie@v1.8.0
        with:
          channel: lts
      - name: build
        shell: bash
        run: cjpm build
